name: Check Spelling

# Minimal workflow structure:
#
# on:
#   push:
#     ...
#   pull_request_target:
#     ...
# jobs:
#   # you only want the spelling job, all others should be omitted
#   spelling:
#     # remove `security-events: write` and `use_sarif: 1`
#     # remove `experimental_apply_changes_via_bot: 1`
#     ... otherwise adjust the `with:` as you wish

on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "**"
  pull_request_target:
    branches:
    - "**"
    tags-ignore:
    - "**"
    types:
    - 'opened'
    - 'reopened'
    - 'synchronize'

jobs:
  spelling:
    name: Check Spelling
    permissions:
      contents: read
      pull-requests: read
      actions: read
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    # concurrency:
    #   group: spelling-${{ github.event.pull_request.number || github.ref }}
    #   # note: If you use only_check_changed_files, you do not want cancel-in-progress
    #   cancel-in-progress: true
    steps:
    - name: check-spelling
      id: spelling
      uses: check-spelling/check-spelling@prerelease
      with:
        suppress_push_for_open_pull_request: 1
        checkout: true
        only_check_changed_files: 1
        check_file_names: 1
        post_comment: 0
        use_magic_file: 1
        report-timing: 1
        extra_dictionary_limit: 10
        check_commit_messages: commits title description
        extra_dictionaries:
          cspell:software-terms/src/software-terms.txt
          cspell:python/src/python/python-lib.txt
          cspell:python/src/python/python.txt
          cspell:java/java.txt
          cspell:node/node.txt
          cspell:python/src/common/extra.txt
          cspell:lorem-ipsum/dictionary.txt
          cspell:fullstack/fullstack.txt
          cspell:html/html.txt
          cspell:aws/aws.txt
          cspell:typescript/typescript.txt
          cspell:filetypes/filetypes.txt
          cspell:node/additional_words.txt
          cspell:django/django.txt
          cspell:cpp/src/stdlib-cpp.txt
          cspell:cpp/src/compiler-clang-attributes.txt
          cspell:bash/bash-words.txt
          cspell:npm/npm.txt
        check_extra_dictionaries: ''
